sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install -U pydocstyle pytest pylint pytest-cov black coveralls
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - ./scripts/test.sh
after_success:
  - coveralls
