sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install -U pydocstyle pytest pylint pytest-cov black coveralls
script:
  - ./scripts/test.sh
after_success:
  - coveralls
